### ISSUE TITLE
pre-trained model checkpoints

### ISSUE THREAD

**Issue by dinalzein** [weinman/MapTD#2]
Hi, I can't find the Pre-trained model checkpoints [here](http://hdl.handle.net/11084/23329)

**Comment by weinman** [comment]
@dinalzein I'm sorry I missed this; my notifications level wasn't set high enough.

I'll look into why the digital library makes them so hard to find. Meanwhile, you should be able to download them from my personal web page:

* [Model checkpoints from paper (ten-fold split; Table III)](https://weinman.cs.grinnell.edu/data/maptd_checkpoints_icdar19.tar.bz2)
* [Model checkpoint (trained on all maps)](https://weinman.cs.grinnell.edu/data/maptd_checkpoints_all.tar.bz2)

Thanks for your interest!
